### ISSUE TITLE
Will you add standalone for GBA too? 

### ISSUE THREAD

**Issue by HJMBgit84** [noword/Emu4VitaPlus#10]
I see that you added standalone versions on V8 but I didn't see the corresponding for GBA, would be great if you added and also for SNES please 🙏🏻

**Comment by noword** [comment]
[gpSP4VitaPlus_0.08.vpk](https://github.com/noword/Emu4VitaPlus/releases/download/v0.08/gpSP4VitaPlus_0.08.vpk)
[Snes9x20024VitaPlus_0.08.vpk](https://github.com/noword/Emu4VitaPlus/releases/download/v0.08/Snes9x20024VitaPlus_0.08.vpk)
[Snes9x20054VitaPlus_0.08.vpk](https://github.com/noword/Emu4VitaPlus/releases/download/v0.08/Snes9x20054VitaPlus_0.08.vpk)
[Snes9x20104VitaPlus_0.08.vpk](https://github.com/noword/Emu4VitaPlus/releases/download/v0.08/Snes9x20104VitaPlus_0.08.vpk)

**Comment by HJMBgit84** [comment]
Awesome, thanks a lot for sharing them and for continuing doing this great
job that a lot of people is enjoying ☺️

**Comment by HJMBgit84** [comment]
Hi,

Just in case mgba has been updated yesterday to 10.4 in case that you want to add also the latest version of that emulation core on emu4vitaplus, thanks
