### ISSUE TITLE
MAME cores crash when you close a game and run another with the same core.

### ISSUE THREAD

**Issue by Snowbro88** [noword/Emu4VitaPlus#11]
Hi again, Sorry to be repetitive but this problem has been happening since the first versions of Emu4vita++, both in the normal and standalone versions and seeing that the project is already looking super cool it would be interesting if this error could be reviewed, I attach the log that is generated when this crash happens.

[Emu4vita+ crash log.zip](https://github.com/user-attachments/files/18002687/Emu4vita%2B.crash.log.zip)

Thank you very much.

**Comment by noword** [comment]
Can you tell which ROM you load first.

**Comment by Snowbro88** [comment]
@noword 

Sure, but I have to make some clarifications first, the MAME 2003 and 2003+ cores have their own problem, many games crash directly, this is solved by running a game that does not crash for example Diet Go Go in MAME 2003+ to be able to modify the core options and disable cyclone, by doing this in theory all the games at least start.

It seems that Emu4vita++ does not support individual configurations, a setting in core options, controls or graphics is applied to all games of the same core.

Now the error inherent to Emu4vita is that when a game is loaded that does work the same Diet Go Go closes and immediately another one is run that does work with the same core such as Dynagear automatically, a c-128 error is obtained in Vita as in the log that I attached.

So the games I tested and you can play them yourself are to run Diet Go Go (dietgo.zip), close it and then run Dynagear (dynagear.zip) with the MAME 2003+ core for example.

Here is a link where you can find the ROMs.

https://archive.org/download/MAME_2003-Plus_Reference_Set_2018/roms/

**Comment by noword** [comment]
Try this one.
Support individual configurations will be in schedule.

[MAME2003Plus4VitaPlus_0.08.vpk.zip](https://github.com/user-attachments/files/18016632/MAME2003Plus4VitaPlus_0.08.vpk.zip)

**Comment by Snowbro88** [comment]
Hi, I can confirm that by doing quick tests the problem seems to have been solved, I didn't get any crash when closing and immediately loading a new game, I suppose the same solution can be applied to the MAME 2000 and 2003 cores.

The Dosbox Pure core had a similar problem but I'm not sure in that case.

Thank you very much for your work and attention.

**Comment by Snowbro88** [comment]
@noword Hi, I'm reopening the topic because after doing more in-depth tests, it seems that the immediate crash problem when closing and loading a new game with the same core has been resolved, but now some games have graphical errors such as a mostly black screen and no audio when loading a new game, something strange as if the memory was not completely cleared and there were remains of the previously loaded game.

Another detail is that the last vpk you left for MAME 2003+ has worse performance than the v0.8 included in the official release, something like 10% less performance.

I hope I'm not a bother, I'm just contributing to get the best possible version of this great project.

**Comment by noword** [comment]
Can you test again.
While I was fixing this "load another rom issue", I was also changing other code.
This caused problems.

[MAME2003Plus4VitaPlus_0.08.vpk.zip](https://github.com/user-attachments/files/18045491/MAME2003Plus4VitaPlus_0.08.vpk.zip)

**Comment by Snowbro88** [comment]
@noword Hi, I'm testing again and I can tell you that the problems I mentioned above still persist.

The immediate error when closing and opening a new game has been resolved, but when running a new game you get graphical and audio errors as if the memory had not been cleaned properly and elements from the previous game remained.

Also the performance in MAME 2003+ is worse than in the official v0.8 release for some reason, like 10%.

**Comment by noword** [comment]
Please tell me the details of your test, which ROM and how you tested it.

**Comment by Snowbro88** [comment]
@noword It seems that the problem occurs when loading, closing and reloading several games, a quick way to reproduce this is for example to run the game Gunforce II (gunforc2.zip) close, run Hook (hook.zip), close and finally run JJ Squakers (jjsquawk.zip).

This way you can see the graphical problem I mentioned, the last game starts but it looks practically black, on other occasions I had graphical or audio problems with different games, it seems like residue from previously loaded games as if the memory was not cleaned properly.

The FBA Lite core, for example, even when loading very heavy games such as CPS3 or PGM, has no problem with this function of closing and loading a new game, it does it perfectly in a matter of seconds.

If you need other tests just let me know.

**Comment by noword** [comment]
Which game you feel is degraded in performance？

**Comment by Snowbro88** [comment]
@noword In general, in all games, you can check it for example with Diet Go Go (dietgo.zip) in the v0.8 release it goes full speed with the CPU at 90% and perfect audio and in the last vpk that you left above the CPU goes to 100% and the audio crackles, you can see it with the PSV Shell plugin.
