### ISSUE TITLE
just request something

### ISSUE THREAD

**Issue by surlup** [noword/Emu4VitaPlus#16]
are there any plans to add newgeocd core to Emu4VitaPlus?

**Comment by noword** [comment]
Plz test it.
Make sure the required BIOS files are under `ux:/data/EMU4VITAPLUS/system/neocd`
[neocd4VitaPlus_0.10.vpk.zip](https://github.com/user-attachments/files/18194154/neocd4VitaPlus_0.10.vpk.zip)

**Comment by surlup** [comment]
> Plz test it. Make sure the required BIOS files are under `ux:/data/EMU4VITAPLUS/system/neocd` If had any problem, tell me the detail. [neocd4VitaPlus_0.10.vpk.zip](https://github.com/user-attachments/files/18194154/neocd4VitaPlus_0.10.vpk.zip)

![WhatsApp Image 2024-12-19 at 00 14 21(1)](https://github.com/user-attachments/assets/aac04ca7-744b-471b-811a-a54d36a48212)

![WhatsApp Image 2024-12-19 at 00 14 21](https://github.com/user-attachments/assets/4f645699-d27f-4468-939c-b90972a0ed47)

this is Amazing can work on vita3k thanks you very-very much, on retroarc i can't run this game, I pray that wherever you are, you are always under God's protection and always healthy.
