### ISSUE TITLE
Add Supafaust core (snes)

### ISSUE THREAD

**Issue by ONElua** [noword/Emu4VitaPlus#19]
Please
https://github.com/libretro/supafaust
https://www.reddit.com/r/vitahacks/comments/14x32l0/release_supafaust_core_for_retroarch/

Supafaust Has support for msu files...

**Comment by noword** [comment]
This core does not support ps vita.
I try to compile & link it, but failed in the end.
EXCEPTION_STACK_OVERFLOW when boot in vita3k.
I change the `sceUserMainThreadStackSize` value to 0x1000000(16M)，same result.
I gave up.

**Comment by ONElua** [comment]
@noword https://github.com/Rinnegatamante/supafaust

**Comment by noword** [comment]
Here it is.
[supafaust4VitaPlus_0.11.vpk.zip](https://github.com/user-attachments/files/18242383/supafaust4VitaPlus_0.11.vpk.zip)

**Comment by ONElua** [comment]
Works
 But it is not loading the msu files

When I try the files compiled by rinnen in Retroarch it works correctly

**Comment by noword** [comment]
The size of msu file in this package is zero.
Is it right?

**Comment by ONElua** [comment]
Yes

**Comment by noword** [comment]
I figuare out. Plz try again.

[Supafaust4VitaPlus_0.11.vpk.zip](https://github.com/user-attachments/files/18243064/Supafaust4VitaPlus_0.11.vpk.zip)

**Comment by ONElua** [comment]
Yeah its works!!!
I hope you can continue working on this core and make improvements

**Comment by Vecinagamer** [comment]
This great work is wonderful, friend, congratulations and Merry Christmas to all of you and your great families, friends.
