### ISSUE TITLE
System Bios

### ISSUE THREAD

**Issue by Zaedisi** [noword/Emu4VitaPlus#6]
Could the description of where the bios goes be clearer. Like does it go in a folder called system in the data folder (ux0:/data/EMU4VITAPLUS/system/mgba) or does it go in the folder in the data start (ux0:/data/EMU4VITAPLUS/mgba) ? And does it just drop in or have to go in a folder pls?

**Comment by noword** [comment]
Just copy all bios files in ux0:/data/EMU4VITAPLUS/system
